### ISSUE TITLE
How to set Recording limit to max 20 seconds in audio-react-recorder

### ISSUE THREAD

**Issue by ladanikevin** [doppelgunner/audio-react-recorder#4]
Please give me suggestion for How to set Recording limit to max 20 seconds in audio-react-recorder

**Comment by ladanikevin** [comment]
Please give me suggestion for How to set Recording limit to max 20 seconds in audio-react-recorder

**Comment by JohnGoodman** [comment]
Hey @ladanikevin, you could set this 20 second limit outside of the recorder if needed. Just create your own timer and programmatically stop the recording and give the user some feedback. Not sure if this will work for your use case, but hoping it helps.

**Comment by vyashh** [comment]
@doppelgunner can you close this issue?
